# Generated by Django 3.2.5 on 2021-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=122)),
                ('text', models.CharField(max_length=122)),
                ('created_at', models.CharField(max_length=122)),
                ('updated_at', models.CharField(max_length=122)),
            ],
        ),
    ]
