# Generated by Django 3.2.5 on 2021-07-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='postUser',
        ),
    ]
